project: 
  type: website
  output-dir: docs
  
  
website: 
  page-navigation: true
  title: ":herb:" 
  site-url: "https://toninif.github.io" 
  repo-url: https://toninif.github.io
  cookie-consent: true
  
  page-footer:
    right: "This page is built with ‚ù§Ô∏è and [Quarto](https://quarto.org/)."
    left: "üá¶üá∑ ‚≠ê‚≠ê‚≠ê"
    
  navbar:
    pinned: true
    right: 
      - icon: globe
        href: https://toninif.github.io/
      - icon: github
        href: https://github.com/toninif
      - icon: twitter
        href: https://twitter.com/toninifer
    left: 
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mi
      - href: https://toninif.github.io/blog_clubdelcodigo/
        text: Club del C√≥digo
      - href: https://toninif.github.io/fernandoBlognini/
        text: Mi blog
      - text: Presentaciones
        menu:
          - href: https://toninif.github.io/ccabierta_2022/conCienciaAbierta2022.html
            text: Congreso ConCiencia Abierta 2022
          - href: https://toninif.github.io/presentacionUBA2022/trabajo_presentacion.html
            text: XIV Congreso Internacional de Investigacion UBA
          - href: https://toninif.github.io/congresoSIP2022/presentacionQ.html
            text: Congreso SIP 2022
      - href: paquetes.qmd
        text: Paquetes
    search: true

format:
  html:
    theme:
      light: journal
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
    from: markdown+emoji




  
